### PR TITLE
Switch to PEP 517 build

### LINKED ISSUE #18: Shift the build process to PEP-517
Evaluate and change the build process to [PEP-517](https://www.python.org/dev/peps/pep-0517/)

### PR DESCRIPTION
**Pull request by Rohan-cod**
## Description

Updated `setup.cfg`, deleted `setup.py`, and added **build time requirements** in `pyproject.toml` to shift the **build process** to `PEP 517`.

Fixes #18

## How Has This Been Tested?

The code has been tested by running all the unit tests using the command `python -m unittest`, validated the PEP 8 formatting using `pycodestyle` and deployed the build to `pypi` to test if it is installed without any errors using `pip`.

- [x] Unit Tests
- [x] PEP 8 Formatting Validation
- [x] pip install `package_name`

### CODE REVIEW

**Comment by srgothi92** [comment]
Can you try deploying the binary to https://test.pypi.org/ and download via pip and confirm everything works without `cython` and `wheel` installation. One more thing that we need to take is what if user upgrades from older build to newer build, does it break anything ?

**Comment by Rohan-cod** [comment]
Hi @srgothi92,
I deployed the package on [pypi](https://pypi.org/project/vcf2fhir-test-517/). Even after adding a `pyproject.toml`, I am still getting the same error - `No module named 'Cython'`. I also tried adding a `MANIFEST.in` to include `pyproject.toml` but still  the same error. I think it can be resolved when `pyrle` is updated.

**Comment by Rohan-cod** [comment]
> One more thing that we need to take care is what if user upgrades from older build to newer build, does it break anything ?

I tested this one just now. First I deployed the package with the older build process and installed it via `pip`. Then I shifted the build process to `PEP 517` and upgraded it. I was able to upgrade it without any errors
Screenshot 2021-06-17 at 10 46 59 PM

**Comment by srgothi92** [comment]
> I deployed the package on [pypi](https://pypi.org/project/vcf2fhir-test-517/). Even after adding a `pyproject.toml`, I am still getting the same error - `No module named 'Cython'`. I also tried adding a `MANIFEST.in` to include `pyproject.toml` but still the same error. I think it can be resolved when `pyrle` is updated.

Can you remove all the changes that you did for this and keep only the changes required for PEP-517 build.

**Comment by Rohan-cod** [comment]
> Can you remove all the changes that you did for this and keep only the changes required for PEP-517 build.

@srgothi92, actually I made all those changes(like adding the `MAINFEST.in` file) on my local machine and then deployed it to `PyPI`. This **pull request** only has the **changes** required for `PEP 517`.

**Review by srgothi92 — APPROVED** [review]
Can you update the Readme file also.

**Comment by Rohan-cod** [comment]
> Can you update the Readme file also.

Hi @srgothi92, can you please tell what needs to be updated in the `README`. Do I need to add information related to `PEP 517` build process?

**Comment by srgothi92** [comment]
> > Can you update the Readme file also.
> 
> Hi @srgothi92, can you please tell what needs to be updated in the `README`. Do I need to add information related to `PEP 517` build process?

Sorry, my bad. This PR is ready to be merged.
 I meant the CHANGELOG file in [this PR](https://github.com/elimuinformatics/vcf2fhir/pull/75), mention we are changing the build process to PEP-517 in this release.

**Review by rhdolin — APPROVED** [review]

**Pull request merged**
