### PR TITLE
Issue #36: Remove 'Human reference sequence assembly version' component from variant observation

### PR DESCRIPTION
**Pull request by theanmolsharma**
Removed the code that created the component LOINC 62374-4

### CODE REVIEW

**Comment by rhdolin** [comment]
@theanmolsharma It looks like some of the checks are failing.

**Comment by theanmolsharma** [comment]
@rhdolin I think the checks are failing because it is expecting the component 'LOINC 62374-4'. to be present in the output file. The checks need to me modified.

**Comment by rhdolin** [comment]
@theanmolsharma Ok. do you need some guidance on how to do that?

**Comment by theanmolsharma** [comment]
@rhdolin I need some guidance.

**Comment by srgothi92** [comment]
> Also, I think it would be better to create a separate issue to make these changes.

How would that help ? Normally, It's part of dev workflow to fix or add test along with the commit in which change was introduced.  Sometimes we can consider to add new tests in separate PR due to time crunch, but failing tests means there is something wrong with code, so it needs to be addressed immediately.

**Comment by srgothi92** [comment]
> I need some guidance.

Can you please provide more details on what guidance or help do you exactly need.

> I think expected results of conversation in test needs to updated.

I agree. You would have to delete those extra blocks from expected output file and fix any other failures that you see because of that.

**Comment by theanmolsharma** [comment]
@srgothi92 @rhdolin  Should I create a separate PR and make changes in the expected output files? These tests are failing because the expected output file contains the component LOINC 62374-4 which shouldn't be there. I think the right course of action would be to create a separate PR to make changes to the expected output file and when that PR is merged, we can re-run the CI on this PR again.

**Comment by srgothi92** [comment]
> Should I create a separate PR and make changes in the expected output files 

I still don't understand what is stopping you to do it as part of this PR ? you can always `amend` your commit and do a force push it would automatically update this PR.

**Comment by theanmolsharma** [comment]
even if I make the changes in this PR. CI tests would still not pass because CI tests are run with test files on the master branch. So unless the master branch is updated, the checks in this PR won't pass.

**Comment by abhishek-jain-1999** [comment]
@rhdolin @srgothi92 @theanmolsharma can I do the part of updating files require to resolve this build issue

**Comment by Rohan-cod** [comment]
> even if I make the changes in this PR. CI tests would still not pass because CI tests are run with test files on the master branch. So unless the master branch is updated, the checks in this PR won't pass.

No @theanmolsharma, this is not what actually happens. If it was the case that CI tests are run with test files on the master branch, then each new pull request would have all its checks as passed. If you will make the changes to the expected output file in this PR itself, all the checks will pass.

**Comment by theanmolsharma** [comment]
@Rohan-cod Thanks for your assistance. I didn't know that. I will make changes and force push to re-run the CI.

**Comment by Rohan-cod** [comment]
> @Rohan-cod Thanks for your assistance. I didn't know that. I will make changes and force push to re-run the CI.

No problem @theanmolsharma 😀

**Comment by theanmolsharma** [comment]
I am closing this PR because my branch got messed up while rebasing. I apologize for the inconvenience. I will create a new branch, make changes and generate a new PR.

**Pull request closed without merging**
